server:
  port: 9080
spring:
  profiles:
    active: @spring.active@
  datasource:
    driver-class-name: org.h2.Driver
    username: 'admin'
    password:
    url: 'jdbc:h2:mem:drawing-program'
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update